name: Events Demo 1

on:
  pull_request:
    types: 
      - opened
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './Workflows & Events/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: './Workflows & Events'

      - name: Test code
        run: npm run test
        working-directory: './Workflows & Events'

      - name: Build code
        run: npm run build
        working-directory: './Workflows & Events'

      - name: Deploy project
        run: echo "Deploying..."
        working-directory: './Workflows & Events'