name: Deployment Exercise 2
on: push

# Esto aplica el directorio a TODOS los jobs y pasos automáticamente
defaults:
  run:
    working-directory: './04 Practice'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './04 Practice/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './04 Practice/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Test code
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './04 Practice/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Deploy code
        run: echo "Deploying..."